export const SPARE_TYPES = [
    "Aceites y grasas",
    "Arandelas",
    "Asientos y fundas",
    "Balizas y luces",
    "Cables de forro de freno y cambio",
    "Cadenas y uniones",
    "Camaras",
    "Caramañolas y portacaramañolas",
    "Caños portasillas",
    "Cintas",
    "Cambios, descarrilador y manijas",
    "Cubiertas",
    "Ejes, cierres y espigas",
    "Engranajes",
    "Manubrios",
    "Frenos",
    "Guantes e indumentaria",
    "Guardabarros",
    "Hombreras - bolsitos",
    "Infladores",
    "Juegos de direccion",
    "Lentes",
    "Llantas",
    "Manijas de freno",
    "Mazas de acero, aluminio y contrapedal",
    "Patines de freno",
    "Pedales",
    "Piñones",
    "Protectores y cinta de llanta",
    "Puños, cubremanubrios y tapones",
    "Rayos y niples",
    "Solucion, parches, kit reparacion y liq. sellador",
    "Tensores y guias de cadenas",
    "Valvulas y accesorios",
    "Rulemanes",
    "O-rings"
]